# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0014_persistentsubsectiongradeoverridehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentsubsectiongradeoverridehistory',
            name='earned_graded_override',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
